/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ayeminoo' at '1/9/18 11:01 PM' with Gradle 2.10
 *
 * @author ayeminoo, @date 1/9/18 11:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
